# Site settings
title: UCSB CS Student Research Colloquium
email: mvigil@cs.ucsb.edu
description: > # this means to ignore newlines until next entry 
    University of California, Santa Barbara
    Computer Science
    Student Research Colloquium

footer_1: University of California, Santa Barbara
footer_2: Department of Computer Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ucsb-cs-student-research-colloquium.github.io" # the base hostname & protocol for your site
github_username: UCSB-CS-Student-Research-Colloquium
permalink: pretty

# Build settings
markdown: kramdown

# Navigation toolbar:
navigation:
    - text: Important dates
      url: /important-dates/
    - text: Speakers
      url: /speakers/
    - text: Contact us
      url: /contact/

collections:
    GradReps: # Collection of GradRep profiles (in /_GradReps/)
        output: true # Each GradRep gets a html webpage
        permalink: /gradrep/:path/
